# General configuration
server:
  port: 31100
  servlet:
    context-path: /doslab
    
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
    
